spring:
  application:
    name: goa-gateway
  profiles:
    # Profile -------------------------------------------------
    active: dev
  # -----------------------------------------------------------
  output:
    ansi:
      enabled: ALWAYS
  cache:
    type: none
  jackson:
    default-property-inclusion: NON_NULL
  cloud:
    gateway:
      #      default-filters:
      #        - StripPrefix=1
      discovery:
        locator:
          enabled: true
          # /tpv-user/**, /tpv-article/**, /tpv-ticket/**
          lower-case-service-id: true
      routes:
        - id: route-goa-user-login
          uri: lb://goa-user
          predicates:
            - Path=/login/**
          filters:
            - name: RewritePath
              args:
                regexp: "^/login(?<segment>/.*)?"
                replacement: "/login${segment}"
        - id: route-goa-user-default
          uri: lb://goa-user
          predicates:
            - Path=/default-ui.css
          filters:
            - RewritePath=/default-ui.css,/default-ui.css
        - id: route-goa-user-oauth2-authorize
          uri: lb://goa-user
          predicates:
            - Path=/oauth2/authorize/**
          filters:
            - name: RewritePath
              args:
                regexp: "^/oauth2(?<segment>/.*)?"
                replacement: "/oauth2${segment}"

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
server:
  forward-headers-strategy: native
  use-forward-headers: true

info:
  app:
    artifact: "@project.artifactId@"
    version: "@project.version@"
    build: "@maven.build.timestamp@"
management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, metrics, loggers
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true
  loggers:
    enabled: true

logging:
  level:
    root: WARN
    es.upm.miw: DEBUG
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true