server:
  port: 8080
  use-forward-headers: true

spring:
  application:
    name: goa-gateway
  profiles:
    # Profile -------------------------------------------------
    active: dev
  # -----------------------------------------------------------
  output:
    ansi:
      enabled: ALWAYS
  cache:
    type: none
  jackson:
    default-property-inclusion: NON_NULL
  cloud:
    gateway:
      routes:
        - id: goa-user
          uri: lb://goa-user
          predicates:
            - Path=/api/goa-user/**
          filters:
            - StripPrefix=2
        - id: goa-engagement
          uri: lb://goa-engagement
          predicates:
            - Path=/api/goa-engagement/**
          filters:
            - StripPrefix=2

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:8080"
              - "https://gestion.ocanabogados.es"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

info:
  app:
    artifact: "@project.artifactId@"
    version: "@project.version@"
    build: "@maven.build.timestamp@"
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: WARN
    es.upm.miw: DEBUG
    org.springframework.cloud.gateway: WARN

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
