server:
  port: 8080
  forward-headers-strategy: native
  use-forward-headers: true

spring:
  application:
    name: goa-gateway
  profiles:
    # Profile -------------------------------------------------
    active: dev
  # -----------------------------------------------------------
  output:
    ansi:
      enabled: ALWAYS
  cache:
    type: none
  jackson:
    default-property-inclusion: NON_NULL
  cloud:
    gateway:
      routes:
        - id: goa-user
          uri: lb://goa-user
          predicates:
            - Path=/goa-user/**
          filters:
            - StripPrefix=1
        - id: oauth2-authorize
          uri: lb://goa-user
          predicates:
            - Path=/oauth2/authorize/**
        - id: login
          uri: lb://goa-user
          predicates:
            - Path=/login/**
        - id: route-goa-user-default
          uri: lb://goa-user
          predicates:
            - Path=/default-ui.css

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:8080"
              - "https://gestion.ocanabogados.es"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

info:
  app:
    artifact: "@project.artifactId@"
    version: "@project.version@"
    build: "@maven.build.timestamp@"
management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, metrics, loggers
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true
  loggers:
    enabled: true

logging:
  level:
    root: WARN
    es.upm.miw: DEBUG
    org.springframework.cloud.gateway: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
